In [1]:
import numpy as np
import statsmodels.api as sm

In [2]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [3]:
x = sm.add_constant(x)

In [4]:
print(x)
print(y)

[[ 1.  0.  1.]
 [ 1.  5.  1.]
 [ 1. 15.  2.]
 [ 1. 25.  5.]
 [ 1. 35. 11.]
 [ 1. 45. 15.]
 [ 1. 55. 34.]
 [ 1. 60. 35.]]
[ 4  5 20 14 32 22 38 43]


In [5]:
model = sm.OLS(y, x)

In [6]:
results = model.fit()

In [7]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     15.56
Date:                Tue, 07 Oct 2025   Prob (F-statistic):            0.00713
Time:                        22:04:47   Log-Likelihood:                -24.316
No. Observations:                   8   AIC:                             54.63
Df Residuals:                       5   BIC:                             54.87
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.5226      4.431      1.246      0.2

C:\Users\Rafael Po\miniconda\envs\myenv\lib\site-packages\scipy\stats\_stats_py.py:1736: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [8]:
print("Coefficient of determination: ", results.rsquared)
print("Adjusted coefficient of determination: ", results.rsquared_adj)
print("Regression coefficients: ", results.params)

Coefficient of determination:  0.8615939258756777
Adjusted coefficient of determination:  0.8062314962259488
Regression coefficients:  [5.52257928 0.44706965 0.25502548]


In [9]:
print("Predicted Response: ", results.fittedvalues, sep='\n')

Predicted Response: 
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [10]:
print("Predicted response:", results.predict(x), sep='\n') 

Predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [11]:
x_new = sm.add_constant(np.arange(10).reshape(-1, 2))
print(x_new)

[[1. 0. 1.]
 [1. 2. 3.]
 [1. 4. 5.]
 [1. 6. 7.]
 [1. 8. 9.]]


In [ ]:
y_new = results.predict(x_new)
print(y_new)