In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [3]:
print(x)

[[ 0  1]
 [ 5  1]
 [15  2]
 [25  5]
 [35 11]
 [45 15]
 [55 34]
 [60 35]]


In [4]:
print(y)

[ 4  5 20 14 32 22 38 43]


In [5]:
model = LinearRegression().fit(x, y)

In [6]:
r_sq = model.score(x, y)
print("Coefficient of determination:", r_sq)
print("Intercept:", model.intercept_)
print("Slope:", model.coef_)

Coefficient of determination: 0.8615939258756775
Intercept: 5.52257927519819
Slope: [0.44706965 0.25502548]


In [9]:
y_pred = model.predict(x)
print("Predicted response:", y_pred, sep="\n")

Predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [11]:
y_pred = model.intercept_ + np.sum(model.coef_ * x, axis=1)
print("Predeicted ResponseL ", y_pred, sep="\n")

Predeicted ResponseL 
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [12]:
x_new = np.arange(10).reshape((-1, 2))
print(x_new)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
y_new = model.predict(x_new)
print(y_new)

[ 5.77760476  7.18179502  8.58598528  9.99017554 11.3943658 ]
